//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consulting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Consulting.Common.Resources.DataFields", typeof(DataFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد حساب های سرفصل.
        /// </summary>
        public static string AccountCount {
            get {
                return ResourceManager.GetString("AccountCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع حساب.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان حساب.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDateFa {
            get {
                return ResourceManager.GetString("BirthDateFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه.
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش اقتصادی.
        /// </summary>
        public static string BusinessTypeID {
            get {
                return ResourceManager.GetString("BusinessTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مشتری.
        /// </summary>
        public static string CustomerHeadFirstName {
            get {
                return ResourceManager.GetString("CustomerHeadFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string CustomerHeadID {
            get {
                return ResourceManager.GetString("CustomerHeadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی مشتری.
        /// </summary>
        public static string CustomerHeadLastName {
            get {
                return ResourceManager.GetString("CustomerHeadLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سپرده.
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سپرده.
        /// </summary>
        public static string DepositTypeDesc {
            get {
                return ResourceManager.GetString("DepositTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سپرده.
        /// </summary>
        public static string DepositTypeID {
            get {
                return ResourceManager.GetString("DepositTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت اقتصادی.
        /// </summary>
        public static string EconomicTypeID {
            get {
                return ResourceManager.GetString("EconomicTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتویات سر فصل.
        /// </summary>
        public static string GLItemContentType {
            get {
                return ResourceManager.GetString("GLItemContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه سرفصل.
        /// </summary>
        public static string GLItemGroup {
            get {
                return ResourceManager.GetString("GLItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرفصل حساب.
        /// </summary>
        public static string GLItemID {
            get {
                return ResourceManager.GetString("GLItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمر سرفصل.
        /// </summary>
        public static string GLItemLifeTimeType {
            get {
                return ResourceManager.GetString("GLItemLifeTimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرخط / بالاخط.
        /// </summary>
        public static string GLItemLineType {
            get {
                return ResourceManager.GetString("GLItemLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام  سرفصل .
        /// </summary>
        public static string GLItemName {
            get {
                return ResourceManager.GetString("GLItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دفتر کل.
        /// </summary>
        public static string GLItemNumber {
            get {
                return ResourceManager.GetString("GLItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سرفصل.
        /// </summary>
        public static string GLItemStatus {
            get {
                return ResourceManager.GetString("GLItemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سرفضل.
        /// </summary>
        public static string GLItemType {
            get {
                return ResourceManager.GetString("GLItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه افتتاح.
        /// </summary>
        public static string GLOpeningType {
            get {
                return ResourceManager.GetString("GLOpeningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس منزل مشتری.
        /// </summary>
        public static string HomeAddressCustomerDetail {
            get {
                return ResourceManager.GetString("HomeAddressCustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن منزل مشتری.
        /// </summary>
        public static string HomePhoneCustomerDetail {
            get {
                return ResourceManager.GetString("HomePhoneCustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل هزینه تنخواه.
        /// </summary>
        public static string ImprestAccount {
            get {
                return ResourceManager.GetString("ImprestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنخواه دار.
        /// </summary>
        public static string ImprestFunder {
            get {
                return ResourceManager.GetString("ImprestFunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اقساط.
        /// </summary>
        public static string InstallmentCount {
            get {
                return ResourceManager.GetString("InstallmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شغل.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح تحصیلات.
        /// </summary>
        public static string LastEducationLevel {
            get {
                return ResourceManager.GetString("LastEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی .
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علت وام.
        /// </summary>
        public static string LoanCauseID {
            get {
                return ResourceManager.GetString("LoanCauseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسهیلات انتخاب شود.
        /// </summary>
        public static string LoanID {
            get {
                return ResourceManager.GetString("LoanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت وام.
        /// </summary>
        public static string LoanStatusID {
            get {
                return ResourceManager.GetString("LoanStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وام.
        /// </summary>
        public static string LoanTitle {
            get {
                return ResourceManager.GetString("LoanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع وام.
        /// </summary>
        public static string LoanTypeID {
            get {
                return ResourceManager.GetString("LoanTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر موجودی.
        /// </summary>
        public static string MaxBalance {
            get {
                return ResourceManager.GetString("MaxBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت خدمت.
        /// </summary>
        public static string MilitaryServiceStatus {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل موجودی.
        /// </summary>
        public static string MinBalance {
            get {
                return ResourceManager.GetString("MinBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل مشتری.
        /// </summary>
        public static string MobileCustomerDetail {
            get {
                return ResourceManager.GetString("MobileCustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور جدید.
        /// </summary>
        public static string ReNewPassword {
            get {
                return ResourceManager.GetString("ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات نقش.
        /// </summary>
        public static string RoleDesc {
            get {
                return ResourceManager.GetString("RoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره برگه.
        /// </summary>
        public static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال شناسنامه.
        /// </summary>
        public static string SeriChar {
            get {
                return ResourceManager.GetString("SeriChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال شناسنامه.
        /// </summary>
        public static string SeriNo {
            get {
                return ResourceManager.GetString("SeriNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت ها.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string SSH {
            get {
                return ResourceManager.GetString("SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح سند.
        /// </summary>
        public static string TransactionHeadDesc {
            get {
                return ResourceManager.GetString("TransactionHeadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح بند سند.
        /// </summary>
        public static string TransactionItemDesc {
            get {
                return ResourceManager.GetString("TransactionItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل .
        /// </summary>
        public static string ZoneID {
            get {
                return ResourceManager.GetString("ZoneID", resourceCulture);
            }
        }
    }
}
