//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consulting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Consulting.Common.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ قابل پرداخت نمیتواند از مبلغ درخواستی بزرگتر باشد.
        /// </summary>
        public static string AcceptedAmountCantBeGreaterThanRequestedAmount {
            get {
                return ResourceManager.GetString("AcceptedAmountCantBeGreaterThanRequestedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0}  با فیلد {1} مطابقت ندارد..
        /// </summary>
        public static string CompareField {
            get {
                return ResourceManager.GetString("CompareField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0}  درست وارد شود..
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول فیلد {0}  می بایست {1} باشد..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول فیلد {0}  می بایست {1} می باشد..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه اشتباه می باشد یا کاربر دسترسی لازم را ندارد..
        /// </summary>
        public static string NotAccessbranch {
            get {
                return ResourceManager.GetString("NotAccessbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه یافت نشد..
        /// </summary>
        public static string NotFoundBranch {
            get {
                return ResourceManager.GetString("NotFoundBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با این مشخصات یافت نشد.
        /// </summary>
        public static string NotuserFound {
            get {
                return ResourceManager.GetString("NotuserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0}  درست وارد شود..
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} می بایست بین {1} و {2} باشد..
        /// </summary>
        public static string RangeCheck {
            get {
                return ResourceManager.GetString("RangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} وارد شود..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  طول فیلد {0}  نمیتواند بیشتر از {1} باشد..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیر فعال است. .
        /// </summary>
        public static string UserNotEnable {
            get {
                return ResourceManager.GetString("UserNotEnable", resourceCulture);
            }
        }
    }
}
